name: Node.js Tests

on:
  push:
    branches: ["Main"]
  pull_request:
    branches: ["Main"]

jobs:
  test:
    runs-on: windows-latest # Más rápido que Windows para CI

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: .
        run: |
          npm ci  # Usa npm ci en lugar de install para builds de CI
        env:
          JWT_SECRET: "secret_for_testing"

      - name: Run tests
        working-directory: .
        run: npm test
        env:
          JWT_SECRET: "secret_for_testing"
          NODE_ENV: "test"
